name: AK
favicon: null
layout_spectrum: 0.11692094011232257
typography_spectrum: 0.4768950496800244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.11446825927123427
  lightness: 0.5906977239064872
  saturation: 0.5820732915308326
  rhythmicContrast: 0.17937899753451347
purpose: []
